---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: centos
lint:
  name: yamllint
platforms:
  - name: centos-icinga2-master
    groups:
      - icinga2master
      - icingaweb2
    image: centos:8
    command: /sbin/init
    privileged: True
  - name: centos-icinga2-satellite
    groups:
      - icinga2satellite
    image: centos:7
    command: /sbin/init
    privileged: True
  - name: centos-icinga2-satclient
    groups:
      - icinga2client
      - icinga2satclient
    image: centos:8
    command: /sbin/init
    privileged: True
  - name: centos-icinga2-std-client
    groups:
      - icinga2client
      - icinga2stdclient
    image: centos:6
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_LIBRARY: ${MOLECULE_PROJECT_DIRECTORY}/plugins/modules
    ANSIBLE_MODULE_UTILS: ${MOLECULE_PROJECT_DIRECTORY}/plugins/module_utils
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
  inventory:
    group_vars:
      all:
        stage: docker
        # ticketsalt in all, used on master and on clients to request a ticket
        icinga2_ticketsalt: aiSee1aan4etho4a
      icinga2master:
        icinga2_admin_email: not@available.invalid
        icinga2_idodb_pass: idodbpass
      icingaweb2:
        apache2_adminhost_https: false
        icingaweb_db_pass: webdbpass
        icingaweb_password_salt: eemoojee8
        icingaweb_admin_pass: password
        icingaweb_roles:
          - name: Testrole
            groups: Testgroup
            permissions: '{{ icingaweb_roles_permissions_default }}'
            filter: "(host_name=*test*|host_name=test*)"
      icinga2satellite:
        icinga_is_satellite: true
        icinga_zone: satellite
      icinga2satclient:
        icinga_parent:
          zone: satellite
          endpoints:
            - "{{ groups.icinga2satellite|first }}"
  lint:
    name: ansible-lint
    options:
      x: ["204"]
verifier:
  name: testinfra
  lint:
    name: flake8
