---
- name: add icinga repo key
  ansible.builtin.get_url:
    url: "https://packages.icinga.com/icinga.key"
    dest: "/usr/share/keyrings/icinga.asc"
    mode: '0644'
    force: true

- name: add icinga repo
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/icinga.asc] https://packages.icinga.com/debian icinga-{{ ansible_distribution_release }} main"

- name: install icinga2 and required packages
  apt:
    name:
      - icinga2
      - icinga2-ido-mysql
      - mailutils
      - python3-mysqldb
    state: present
  notify: restart icinga2
