---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: default
platforms:
  - name: debian-icinga2-master
    groups:
      - icinga2master
      - icingaweb2
    image: debian:12
    command: /lib/systemd/systemd
    privileged: True
  - name: debian-icinga2-satellite
    groups:
      - icinga2satellite
    image: debian:11
    command: /lib/systemd/systemd
    privileged: True
  - name: debian-icinga2-satclient
    groups:
      - icinga2client
      - icinga2satclient
    image: debian:10
    command: /sbin/init
    privileged: True
  - name: debian-icinga2-std-client
    groups:
      - icinga2client
      - icinga2stdclient
    image: debian:12
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_LIBRARY: ${MOLECULE_PROJECT_DIRECTORY}/plugins/modules
    ANSIBLE_MODULE_UTILS: ${MOLECULE_PROJECT_DIRECTORY}/plugins/module_utils
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
  inventory:
    group_vars:
      all:
        stage: docker
        # ticketsalt in all, used on master and on clients to request a ticket
        icinga2_ticketsalt: aiSee1aan4etho4a
        # exclude checking for /var/molecule globally
        icinga2_checks_disk_exclude_extra:
          - /var/molecule
      icinga2master:
        icinga2_admin_email: not@available.invalid
        icinga2_idodb_pass: idodbpass
      icingaweb2:
        apache2_adminhost_https: false
        icingaweb_db_pass: webdbpass
        icingaweb_password_salt: eemoojee8
        icingaweb_admin_pass: password
        icingaweb_roles:
          - name: Testrole
            groups: Testgroup
            permissions: "module/grafana, module/monitoring, monitoring/command/schedule-check, monitoring/command/acknowledge-problem, monitoring/command/remove-acknowledgement, monitoring/command/comment/*, monitoring/command/comment/add, monitoring/command/downtime/*, monitoring/command/downtime/schedule, monitoring/command/downtime/delete"
            filter: "(host_name=*test*|host_name=test*)"
      icinga2satellite:
        icinga_is_satellite: true
        icinga_zone: satellite
      icinga2satclient:
        icinga_parent:
          zone: satellite
          endpoints:
            - "{{ groups.icinga2satellite|first }}"
verifier:
  name: testinfra
